import render_ant_icons as ant_icons
import render_antd as antd
import render_html as html

Header, Content, Footer, Sider = (
    antd.Layout.Header,
    antd.Layout.Content,
    antd.Layout.Footer,
    antd.Layout.Sider,
)


def app():
    return antd.Layout(
        [
            Sider(
                [
                    html.div(className="logo"),
                    antd.Menu(
                        items=[
                            {
                                "label": "nav 1",
                                "key": "1",
                                "icon": ant_icons.UserOutlined([]),
                            },
                            {
                                "label": "nav 2",
                                "key": "2",
                                "icon": ant_icons.VideoCameraOutlined([]),
                            },
                            {
                                "label": "nav 3",
                                "key": "3",
                                "icon": ant_icons.UploadOutlined([]),
                            },
                            {
                                "label": "nav 4",
                                "key": "4",
                                "icon": ant_icons.BarChartOutlined([]),
                            },
                            {
                                "label": "nav 5",
                                "key": "5",
                                "icon": ant_icons.CloudOutlined([]),
                            },
                            {
                                "label": "nav 6",
                                "key": "6",
                                "icon": ant_icons.AppstoreOutlined([]),
                            },
                            {
                                "label": "nav 7",
                                "key": "7",
                                "icon": ant_icons.TeamOutlined([]),
                            },
                            {
                                "label": "nav 8",
                                "key": "8",
                                "icon": ant_icons.ShopOutlined([]),
                            },
                        ],
                        theme="dark",
                        mode="inline",
                        defaultSelectedKeys=["4"],
                    ),
                ],
                style={
                    "overflow": "auto",
                    "height": "100vh",
                    "position": "fixed",
                    "left": 0,
                },
            ),
            antd.Layout(
                [
                    Header(className="site-layout-background", style={"padding": 0}),
                    Content(
                        html.div(
                            [
                                "...",
                                html.br(),
                                "Really",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "long",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "...",
                                html.br(),
                                "content",
                            ],
                            className="site-layout-background",
                            style={"padding": 24, "textAlign": "center"},
                        ),
                        style={"margin": "24px 16px 0", "overflow": "initial"},
                    ),
                    Footer(
                        "Ant Design ©2018 Created by Ant UED",
                        style={"textAlign": "center"},
                    ),
                ],
                className="site-layout",
                style={"marginLeft": 200},
            ),
        ]
    )
